## Discussion and Conclusion

\quad Understanding the educational requirements of a  job position is essential for the employer to set standards to ensure an applicant is able to perform their task properly, and also for the applicant to filter jobs where they can meet that standard. Thus, filtering using educational requirements helps save time and money that goes into hiring adequate personnel and applicants finding a job they can perform.  Our team analyzed a subset of the 2018 DataFest dataset, job posting information from Indeed, and found that nearly half had no attributed educational requirements. As a team we decided  to investigate which factors play a significant role in determining the education requirements for a job posting, and if we could create a model to predict education requirements.

\quad The 2018 DataFest dataset included numerous city, state, and country data, however our team analyzed a subset of the data just from Los Angeles, CA  which reduced variability  and the large dimensionality of the data. Our dataset started with about 15 features and after performing exploratory data analysis and correlation matrices we identified the four most important features: average overall rating, experience required, estimated salary, and number of reviews. We then used these features to create a simple logistic regression classification model with education requirement as our outcome variable with two possible outcomes: high school, or higher education. Our model was able to predict with a testing accuracy around 80%. Analyzing the classifier’s confusion matrix we found the model predicted both levels equally well as there is not a big difference between the number of false positives and false negatives.
	
\quad In our analysis of our dataset there were some issues which could have impacted our final prediction accuracy, mainly our treatment of high school education job postings being underrepresented and maintaining outliers. During our exploratory data analysis we found that within the outcome variable education requirement the high school level was severely underrepresented in our data with only 4,000 compared to roughly 11,000 observations. To overcome this our team decided to use the oversampling method to increase the high school level to 11,000 observations. Due to this artificial inflation of the minority level, this could have increased the likelihood of our model overfitting to high school, since it makes exact copies of the minority class. In the future to avoid this our team would need more data that has a high school education requirement. Our team also noticed that there were some fairly large leverage values, however upon their deletion our model performance decreased. As a result, to maximize the accuracy of our predictions we left them in, however in the future our team would like to analyze these points further to better understand their effect on the model predictions, and why their impact is so great.

\quad Education requirement is an important variable in job postings to both the employer and applicant. Our team was able to find that average overall rating, experience required, estimated salary, and number of reviews play a significant role in determining the education requirements for a job posting in Los Angeles, CA, and created a logistic model using these predictors to predict education requirements with an accuracy of around 80%. Perhaps in future projects, more variables can be explored, and more enriched data could be added to the current dataset to improve the accuracy of the model.
